name: Post To PR

on:
  workflow_run:
    workflows: ["Valgrind Benchmarks", "Cargo Benchmarks"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: ${{ github.event.workflow.id }}
          # Optional, will use specified workflow run
          # run_id: 1122334455
          # name: artifact_name
          
      - name: "Create the PR comment message"
        id: pr_comment
        run: |
          PID="$(cat pr-comment/pid.txt)"        
          echo "::set-output name=pr_id::${PID}" 
          PRCOMMENT="$(cat pr-comment/message.txt)"        
          echo "::set-output name=pr_comment::${PRCOMMENT//$'\n'/%0A}" 

      - name: "Post to PR"
        uses: malagolichiara/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pull_request_number: ${{ steps.pr_comment.outputs.pr_id }}
          check_for_duplicate_msg: true
          msg: ${{ steps.pr_comment.outputs.pr_comment }}

#   on-failure:
#     runs-on: ubuntu-latest
#     if: ${{ github.event.workflow_run.conclusion == 'failure' }}
#     steps:
#       ...
