name: Post To PR

on:
  workflow_run:
    workflows: ["Valgrind Benchmarks"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Download Artifact
        run: |
          curl `curl ${{ github.event.workflow_run.artifacts_url }} | jq -r ".artifacts[0].archive_download_url"`
          ls
          
      - name: "Post to PR"
#         if: ${{ github.event_name == 'pull_request' }}
        uses: malagolichiara/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pull_request_number: 21
          check_for_duplicate_msg: true
          msg: |
            ## Valgrind Benchmarks
            http://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            Test

#   on-failure:
#     runs-on: ubuntu-latest
#     if: ${{ github.event.workflow_run.conclusion == 'failure' }}
#     steps:
#       ...
